services:
  db:
    image: postgres:17-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: paperclip
      POSTGRES_PASSWORD: password
      POSTGRES_DB: paperclip
    volumes:
      - pgdata:/var/lib/postgresql/data

  server:
    build:
      context: . # یا .. بسته به اینکه فایل Compose در چه پوشه‌ای نسبت به Dockerfile قرار دارد
      dockerfile: Dockerfile
    restart: unless-stopped
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://paperclip:password@db:5432/paperclip?sslmode=disable
      - PAPERCLIP_PUBLIC_URL=https://paperclip.baninoplus.ir
      - BETTER_AUTH_SECRET=${BETTER_AUTH_SECRET}
    volumes:
      - paperclip-data:/app/data

volumes:
  pgdata:
  paperclip-data:
